# Generated by Django 5.2 on 2025-05-19 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_details', to='api.login'),
        ),
    ]
