# Generated by Django 5.2 on 2025-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Price', models.IntegerField()),
                ('category', models.CharField(choices=[('main', 'Main Dish'), ('side', 'Side Dish'), ('drink', 'Drinks'), ('snack', 'Snacks')], max_length=100)),
            ],
        ),
    ]
